#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root!" 
   exit 1
fi

mkdir /etc/libvirt/hooks
wget 'https://raw.githubusercontent.com/PassthroughPOST/VFIO-Tools/master/libvirt_hooks/qemu' -O /etc/libvirt/hooks/qemu
chmod +x /etc/libvirt/hooks/qemu
systemctl restart libvirtd

# Check for Libvirt Hook Helper. If missing, prompt to install.
if [ ! -x "/etc/libvirt/hooks/qemu" ]
then
    echo "Libvirt hook helper cannot be found or is not executable. Installation appears to have failed!"
    exit 1
fi

echo "Installed Libvirt hook helper!"
exit 0
